### ISSUE TITLE
Allow URLs in `!recommend` commands

### ISSUE THREAD

**Issue by anand2312** [anand2312/utilitybot#15]
As the recommend command uses APIs for all content, users are a little restriced (especially in the case of music, where it might be convenient to send a youtube URL instead)
These commands should allow passing a URL instead of a name, and if the URL is passed it should be directly saved instead of querying the API.

Possible challenge I can think of right now is that the `user_content` table has a NOT NULL constraint on the content_name field so we'd have to figure out a way to resolve a name for them.

**Comment by anand2312** [comment]
A URL converter already exists in [`bot.utils.converters`](https://github.com/anand2312/utilitybot/blob/0e9ce94a3872be20a976c3b80d8babc78e591908/bot/utils/converters.py#L22)

**Comment by shriram-sg** [comment]
Sounds fun, I'll do it
