### ISSUE TITLE
Music recommendations

### ISSUE THREAD

**Issue by anand2312** [anand2312/utilitybot#6]
Similar command system to #5

**Comment by shriram-sg** [comment]
Searching for a Song - Completed

**Comment by shriram-sg** [comment]
Music recommendation feature - Completed

Is anything else remaining for the music commands?

**Comment by anand2312** [comment]
> 
> 
> Music recommendation feature - Completed
> 
> Is anything else remaining for the music commands?

@Windsmith Nope, feel free to PR
There's also the change in implementation for the recommendation feature as we'd discussed but that can be in another PR (or this one, doesn't matter too much)
